### ISSUE TITLE
Same foreign table for many attributes in a table

### ISSUE THREAD

**Issue by JLebouvier** [HabeltWi/AutoForm#5]
The configuration of the form (Relational value) does not work if a foreign table is used several times in the same table. A single field in the correct configuration.

For example : 
MyTable
- att1 : Id
- att2 : UserForWork1  -> FK Name : rel1 ; FK table : MyTableOfValues ; FK Field : key
- att3 : UserForWork2  -> FK Name : rel2 ; FK table : MyTableOfValues ; FK Field : key
- att4 : UserForWork3  -> FK Name : rel3 ; FK table : MyTableOfValues ; FK Field : key

MyTableOfValues (list of users)
- key
- value

Thanks

**Comment by HabeltWi** [comment]
Hello JLebouvier

I'm sorry for not getting back to you sooner. If I understood you correctly, the form is only displaying one of the fields with a relation correctly while the others remain blank?
